name: .NET

on:
  pull_request:
    branches: [ master, dev ]
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Iwentys.sln
    - name: Build
      run: dotnet build Source/Iwentys.sln --no-restore
    - name: Test
      run: dotnet test Source/Iwentys.sln --no-build --verbosity normal